# Generated by Django 5.1.15 on 2026-09-21 03:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('suit_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mask_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('issuer', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('open', '开放'), ('closed', '已关')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_issues', to='core.greenhouse')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('greenhouse', 'work_date'), name='uniq_open_ppe_issue_per_greenhouse_day')],
            },
        ),
    ]
